-   id: seed-isort-config
    name: seed isort known_third_party
    description: Statically populate the `known_third_party` `isort` setting.
    entry: seed-isort-config
    language: python
    always_run: true
    pass_filenames: false
    minimum_pre_commit_version: 0.14.0
